/**
 * Lennox alert `code` -> human-readable name. Not documented by Lennox, but
 * reverse-engineered by the open-source lennoxs30api project:
 * https://github.com/PeteRager/lennoxs30api/blob/master/lennoxs30api/lennox_errors.py
 * Used as a fallback when the device's own `userMessage` is blank (common for
 * info-priority / persistent notices).
 */
export const ALERT_CODE_NAMES: Record<number, string> = {
  10: "Unknown Device Detected",
  11: "Missing Device",
  12: "Indoor Unit Not Detected",
  13: "Duplicate Comfort Sensor ID",
  14: "Too Many Devices Of The Same Type",
  15: "Parameter Mismatch Detected For Device",
  18: "Low Ambient HP Heat Lockout",
  19: "High Ambient Auxiliary Heat Lockout",
  20: "Protocol Upgrade Required",
  21: "Incompatible Equipment Detected",
  29: "Over Temperature Protection",
  30: "Low Temperature Protection",
  31: "Lost Communication With Device",
  32: "Device Resetting",
  34: "Must Program Unit Capacity For Device",
  35: "Incorrect Operation Of Device",
  36: "Heating When Not Requested",
  37: "Cooling When Not Requested",
  38: "Not Heating When Requested",
  39: "Not Cooling When Requested",
  40: "HP Heating Lockout",
  41: "Device Control Board Replaced",
  105: "Communication Error",
  110: "GF Low AC Line Voltage",
  111: "GF Line Polarity Reversed",
  112: "GF No Ground Connection",
  113: "GF High AC Line Voltage",
  114: "AC Line Frequency/Distortion Error",
  115: "Low Secondary (24VAC) Voltage",
  116: "IU High Secondary (24VAC) Voltage",
  117: "IU Poor Ground",
  120: "Unresponsive Device",
  124: "Tstat Lost Communication To Smarthub",
  125: "Control Hardware Error",
  126: "Control Internal Communication Error",
  130: "Configuration Jumper Missing",
  131: "Corrupted Control Parameters",
  132: "Device Control Software Fault",
  134: "Reset",
  180: "Outdoor Temperature Sensor Error",
  181: "OU Suction Pressure Transducer Fault",
  182: "OU Suction Temperature Sensor Fault",
  183: "OU Liquid Pressure Sensor Error",
  184: "OU Liquid Temperature Sensor Error",
  200: "GF Rollout Limit Switch Open",
  201: "IU Blower Motor Fault",
  202: "IU Blower Motor & Unit Size Mismatch",
  203: "IU Invalid Size Unit Code",
  204: "GF Check Gas Valve",
  205: "GF Gas Valve Relay Contact Closed",
  206: "GF Gas Valve 2nd Stage Relay Fault",
  207: "GF HSI Sensed Open",
  223: "GF Low Pressure Switch Open",
  224: "GF Low Pressure Switch Stuck Closed",
  225: "GF High Pressure Switch Failed to Close",
  226: "GF High Pressure Switch Stuck Closed",
  227: "GF Low Pressure Switch Open in Run Mode",
  228: "GF Inducer Calibration Issue",
  229: "GF Ignition On High Fire",
  240: "GF Low Flame Current - Run Mode",
  241: "GF Flame Out Of Sequence-Still Present",
  250: "GF Primary Limit Switch Open",
  252: "IU Discharge Air Temperature High",
  270: "GF Flame Failed To Ignite",
  271: "GF Low Press Switch Open",
  272: "GF Low Press Switch Open Run Mode",
  273: "GF Flame Fail In Run Mode",
  274: "GF Primary Limit Switch Open",
  275: "GF Flame Out Of Seq. No Flame",
  276: "GF Calibration Failure",
  290: "GF Ignition Circuit Fault",
  291: "GF Heat Airflow Below Min",
  292: "ID Blower Motor Start Fault",
  294: "GF Inducer Motor Overcurrent",
  295: "ID Blower Over Temperature",
  310: "Discharge Air Temp Sensor Error",
  311: "GF Heat Rate Reduced To Match Airflow",
  312: "Reduced Airflow-Indoor Blower Cutback",
  313: "Indoor/Outdoor Unit Capacity Mismatch",
  330: "Link Relay Problem",
  331: "RSBus Communication Link Problem",
  344: "GF IFC Relay Y1 Stuck",
  345: "Relay O Failure",
  346: "AH HP Jumper Not Removed",
  347: "IU or EIM Relay Y1 Fault",
  348: "IU Relay Y2 Fault",
  349: "GF IFC Error Check Jumper O To R",
  350: "AH Electric Heat Not Configured",
  351: "AH Electric Heat Stage 1 Fault",
  352: "AH Electric Heat Stage 2 Fault",
  353: "AH Electric Heat Stage 3 Fault",
  354: "AH Electric Heat Stage 4 Fault",
  355: "AH Electric Heat Stage 5 Fault",
  356: "Sequencer Failed to Close",
  357: "Sequencer Stuck Closed",
  358: "AH Control Error - Check Jumper O To R",
  370: "GF Interlock Switch Open",
  371: "AH Float Switch Sensed Open",
  380: "EIM Interlock Relay Fault",
  381: "EIM Interlock Relay Stuck",
  382: "EIM Relay W1 Fault",
  400: "OU LSOM Compressor Internal Overload Tripped",
  401: "OU Compressor Long Run Cycle",
  402: "OU System Pressure Trip",
  403: "OU Compressor Short-Cycling",
  404: "OU Compressor Rotor Locked",
  405: "OU Compressor Open Circuit",
  406: "OU Compressor Open Start Circuit",
  407: "OU Compressor Open Run Circuit",
  408: "OU Compressor Contactor Welded",
  409: "OU Control Board Low 24VAC",
  410: "OU Open Low Pressure Switch",
  411: "OU Low Pressure Switch Strikes Lockout",
  412: "OU Open High Pressure Switch",
  413: "OU High Pressure Switch Strikes Lockout",
  414: "OU High Discharge Line Temperature",
  415: "OU High Discharge Line Temp Strikes Lockout",
  416: "OU Coil Sensor Faulty",
  417: "OU Discharge Sensor Faulty",
  418: "OU EIM W Output Hardware Fault",
  419: "OU EIM W Output Hardware Fault Lockout",
  420: "AH EIM Defrost Out Of Cycle",
  421: "OU EIM W External Miswiring Fault",
  422: "OU Compressor Top Cap Switch Open",
  423: "OU Inverter CT Circuit Fault",
  424: "OU Liquid Line Sensor Faulty",
  425: "OU Compressor Speed Limited By OD Temperature",
  426: "OU Excessive Inverter Alarms",
  427: "OU Inverter DC Peak Fault",
  428: "OU Inverter High Main Input Current",
  429: "OU Inverter DC Link Low Voltage",
  430: "OU Inverter Compressor Startup fail",
  431: "OU Inverter PFC Fault",
  432: "OU Inverter DC Link High Voltage",
  433: "OU Inverter Compressor Overcurrent",
  434: "OU Inverter Communication Error To Main Control",
  435: "OU Inverter EEPROM Checksum Fault",
  436: "OU Inverter High Heat-Sink Temperature",
  437: "OU Inverter Heat-Sink Temp Sensor Fault",
  438: "OU Inverter PFC Input Overcurrent",
  439: "OU Inverter Compressor Slowdown - High Input Current",
  440: "OU Inverter Compressor Slowdown - High Heat-Sink Temperature",
  441: "OU Inverter Compressor Slowdown - High Compressor Current",
  442: "OU Compressor Top Cap Switch Strikes Lockout",
  443: "OU MUC Unit Code To Inverter Model Mismatch",
  444: "HP Reversing Valve Relay Or Solenoid Fault",
  446: "OU Low Suction Pressure Fault",
  447: "OU High Liquid Line Temperature",
  448: "OU High Liquid Line Temp Strikes Lockout",
  500: "PA Differential Pressure Sensor Fault",
  501: "PA UV Sensor Fault",
  502: "PA UV Lamp Off",
  503: "PA Filter Life At 10%",
  504: "PA Filter Life At 0%",
  505: "PA Model Selection Changed",
  506: "PA Lamp At 0% life",
  507: "PA Filter Calibration Failure",
  530: "ZS Low Damper 24VAC Voltage",
  532: "ZS Zoning Pressure Switch Opened (High Pressure)",
  542: "ZS Zone 1 Temp Sensor Fault",
  543: "ZS Zone 2 Temp Sensor Fault",
  544: "ZS Zone 3 Temp Sensor Fault",
  545: "ZS Zone 4 Temp Sensor Fault",
  546: "ZS Parameters resetting from restored power",
  547: "ZS Parameters resetting from system interruption",
  548: "ZS Humidity Sensor Error",
  551: "ZS Zone Sensor Lost Communication",
  600: "Load Shed Event",
  601: "OU Low Ambient Operational Lockout",
  602: "OD Unit High Ambient Operational Lockout",
  603: "Service Alert",
  604: "Cooling Capacity Degradation",
  610: "Low Room Temperature Detected",
  611: "High Room Temperature Detected",
  700: "Thermostat  Temp Sensor Error",
  701: "Thermostat Temp Above Limit",
  702: "The thermostat is reading indoor temperatures below the pre-programmed limit",
  703: "Thermostat Humid Sensor Error",
  704: "The thermostat is reading indoor humidity levels above the pre-programmed limit",
  705: "The thermostat is reading indoor humidity levels below the pre-programmed limit",
  801: "Lost Communication with Server",
  802: "Lost Wireless Connection with WAP",
  900: "Temperature Control Error",
  901: "Inconsistent Indoor Temp",
  999: "Ohm check - The ohm reading in the system is either too high or too low",
  65537: "Missing Base",
  65538: "Missing Mag Mount Base",
  65539: "Thermostat Lost Connection Or Internal Fault",
  65540: "Missing HD wall display",
  65541: "Download Failed",
  65542: "Update Failed",
  65543: "Firmware Updated",
  65544: "More Than 8 Tstats In A Group",
  65545: "Cooling Capacity Alert",
};

export function alertCodeName(code: number): string | undefined {
  return ALERT_CODE_NAMES[code];
}
